import { createHash } from "node:crypto";

export const COMPILER_VERSION = "ASTER-ONTOLOGY-COMPILER-0.1.0";
export type DiagnosticSeverity = "ERROR" | "WARNING" | "INFO";
export type DiagnosticPhase = "LEXICAL" | "CONTEXT" | "REFERENCE" | "DEPENDENCY" | "SEMANTIC_TYPE" | "FORMULA_RESOLUTION" | "REACHABILITY" | "CONSISTENCY" | "ARTIFACT";
export interface Diagnostic { diagnosticId: string; severity: DiagnosticSeverity; phase: DiagnosticPhase; conceptId?: string; formulaId?: string; variantId?: string; sourceLocation?: string; message: string; relatedObjects?: readonly string[]; }
export interface SeedManifest { manifestId: string; manifestVersion: string; status: "DRAFT" | "RELEASE_CANDIDATE"; semanticVersion: string; ontologyVersion: string; baseReleaseId?: string | null; sourceReferences: readonly Record<string, unknown>[]; constraints: readonly Record<string, any>[]; concepts: readonly Record<string, any>[]; relationships: readonly Record<string, any>[]; formulaFamilies: readonly Record<string, any>[]; }
interface TypeInfo { dimension: string; measure?: string; currencyRequired: boolean; }
const error = (phase: DiagnosticPhase, message: string, extra: Partial<Diagnostic> = {}): Diagnostic => ({ diagnosticId: `${phase}_${message}`.replace(/[^A-Za-z0-9_]+/g, "_").slice(0, 180), severity: "ERROR", phase, message, ...extra });
function stable(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; const o = value as Record<string, unknown>; return `{${Object.keys(o).sort().map(k => `${JSON.stringify(k)}:${stable(o[k])}`).join(",")}}`; }
function normalizeAlias(value: string): string { return value.normalize("NFKC").trim().toLocaleLowerCase("en-US"); }
function contextKey(c: any = {}): string { return ["accountingFramework","jurisdiction","industry","entityType","reportingBasis","securityClass","currency"].map(k => `${k}=${c[k] ?? "*"}`).join("|"); }
function contextsOverlap(a: any = {}, b: any = {}): boolean { for (const k of ["accountingFramework","jurisdiction","industry","entityType","reportingBasis","securityClass","currency"]) if (a[k] && b[k] && a[k] !== b[k]) return false; return true; }
function expressionType(node: any, inputs: Map<string, TypeInfo>, diagnostics: Diagnostic[]): TypeInfo | undefined {
  if (!node || typeof node !== "object") { diagnostics.push(error("SEMANTIC_TYPE", "Expression node is missing or invalid.")); return; }
  switch (node.kind) {
    case "INPUT": { const t = inputs.get(node.inputName); if (!t) diagnostics.push(error("SEMANTIC_TYPE", `Unbound expression input: ${node.inputName}.`)); return t; }
    case "CONSTANT": return node.unitSemantics ? { dimension: node.unitSemantics.dimension, measure: node.unitSemantics.measureSemantics, currencyRequired: !!node.unitSemantics.currencyRequired } : { dimension: "DIMENSIONLESS", measure: "RATIO", currencyRequired: false };
    case "NEGATE": return expressionType(node.operand, inputs, diagnostics);
    case "ADD": case "SUBTRACT": {
      const l = expressionType(node.left, inputs, diagnostics), r = expressionType(node.right, inputs, diagnostics); if (!l || !r) return;
      const compatible = l.dimension === r.dimension || (l.dimension === "RATE" && ["RATIO","DIMENSIONLESS"].includes(r.dimension)) || (r.dimension === "RATE" && ["RATIO","DIMENSIONLESS"].includes(l.dimension));
      if (!compatible || l.currencyRequired !== r.currencyRequired) diagnostics.push(error("SEMANTIC_TYPE", `Incompatible ${node.kind} dimensions: ${l.dimension} and ${r.dimension}.`));
      return compatible ? (l.dimension === "RATE" || r.dimension === "RATE" ? { dimension: "RATE", measure: "RATE", currencyRequired: false } : l) : undefined;
    }
    case "MULTIPLY": {
      const l = expressionType(node.left, inputs, diagnostics), r = expressionType(node.right, inputs, diagnostics); if (!l || !r) return;
      if (l.dimension === "DIMENSIONLESS" || l.dimension === "RATIO") return r;
      if (r.dimension === "DIMENSIONLESS" || r.dimension === "RATIO") return l;
      if ((l.dimension === "RATE" && r.dimension === "RATE")) return { dimension: "RATIO", measure: "RATIO", currencyRequired: false };
      if (l.dimension === "CURRENCY_AMOUNT" && r.dimension === "SHARE_QUANTITY") return { dimension: "PRICE", measure: "POINT_IN_TIME", currencyRequired: true };
      diagnostics.push(error("SEMANTIC_TYPE", `Unsupported multiplication dimensions: ${l.dimension} * ${r.dimension}.`)); return;
    }
    case "DIVIDE": {
      const l = expressionType(node.left, inputs, diagnostics), r = expressionType(node.right, inputs, diagnostics); if (!l || !r) return;
      if (r.dimension === "DIMENSIONLESS" || r.dimension === "RATIO") return l;
      if (l.dimension === "CURRENCY_AMOUNT" && r.dimension === "SHARE_QUANTITY") return { dimension: "PRICE", measure: "POINT_IN_TIME", currencyRequired: true };
      if (l.dimension === r.dimension) return { dimension: "RATIO", measure: "RATIO", currencyRequired: false };
      diagnostics.push(error("SEMANTIC_TYPE", `Unsupported division dimensions: ${l.dimension} / ${r.dimension}.`)); return;
    }
    case "POWER": {
      const b = expressionType(node.base, inputs, diagnostics), e = expressionType(node.exponent, inputs, diagnostics); if (!b || !e) return;
      if (e.dimension !== "DIMENSIONLESS" && e.dimension !== "RATIO") diagnostics.push(error("SEMANTIC_TYPE", "Power exponent must be dimensionless."));
      if (b.dimension !== "DIMENSIONLESS" && b.dimension !== "RATIO" && b.dimension !== "RATE") diagnostics.push(error("SEMANTIC_TYPE", "Power base must be a dimensionless rate expression."));
      return { dimension: "DIMENSIONLESS", measure: "RATIO", currencyRequired: false };
    }
    default: diagnostics.push(error("LEXICAL", `Unknown expression node kind: ${String(node.kind)}.`)); return;
  }
}
function stageLexical(s: SeedManifest, d: Diagnostic[]) { if (!/^\d+\.\d+\.\d+$/.test(s.semanticVersion)) d.push(error("LEXICAL", "semanticVersion must use SemVer MAJOR.MINOR.PATCH.")); const ids = new Set<string>(); for (const c of s.concepts) { if (!/^concept_[a-z0-9_]+$/.test(c.conceptId ?? "")) d.push(error("LEXICAL", `Invalid concept ID: ${c.conceptId}.`, { conceptId: c.conceptId })); if (ids.has(c.conceptId)) d.push(error("LEXICAL", `Duplicate concept ID: ${c.conceptId}.`, { conceptId: c.conceptId })); ids.add(c.conceptId); for (const k of ["canonicalName","definition","realm","role","unitSemantics","effectiveDuring"]) if (!c[k]) d.push(error("LEXICAL", `Missing ${k} on concept ${c.conceptId}.`, { conceptId: c.conceptId })); } }
function stageContext(s: SeedManifest, d: Diagnostic[]) { const aliases = new Map<string,string[]>(); for (const c of s.concepts) for (const a of c.aliases ?? []) { const key = `${normalizeAlias(a.normalizedValue ?? a.value)}|${contextKey(a.applicability)}`; aliases.set(key, [...(aliases.get(key) ?? []), c.conceptId]); } for (const [key, ids] of aliases) if (new Set(ids).size > 1) d.push(error("CONTEXT", `Alias collision under overlapping context: ${key}.`, { relatedObjects: ids })); for (const c of s.concepts) for (const a of c.aliases ?? []) if (a.applicability && !contextsOverlap(c.applicability, a.applicability)) d.push(error("CONTEXT", `Alias applicability conflicts with concept: ${a.value}.`, { conceptId: c.conceptId })); }
function stageReferences(s: SeedManifest, d: Diagnostic[]) { const concepts = new Set(s.concepts.map(c => c.conceptId)), sources = new Set(s.sourceReferences.map((x:any)=>x.sourceReferenceId)), constraints = new Set(s.constraints.map((x:any)=>x.constraintId)); for (const f of s.formulaFamilies) for (const v of f.variants ?? []) { if (!concepts.has(v.targetConceptId)) d.push(error("REFERENCE", `Formula target does not exist: ${v.targetConceptId}.`, { formulaId:v.formulaId,variantId:v.variantId })); for (const i of v.inputs ?? []) if (!concepts.has(i.conceptId)) d.push(error("REFERENCE", `Formula input concept does not exist: ${i.conceptId}.`, { formulaId:v.formulaId,variantId:v.variantId })); for (const p of v.provenance ?? []) if (!sources.has(p)) d.push(error("REFERENCE", `Unknown formula provenance source: ${p}.`, { formulaId:v.formulaId })); for (const c of v.constraints ?? []) if (!constraints.has(c)) d.push(error("REFERENCE", `Unknown formula constraint: ${c}.`, { formulaId:v.formulaId })); } }
function stageDependencies(s: SeedManifest, d: Diagnostic[]) { const g = new Map<string,Set<string>>(); for (const c of s.concepts) g.set(c.conceptId,new Set()); for (const f of s.formulaFamilies) for (const v of f.variants ?? []) for (const i of v.inputs ?? []) g.get(v.targetConceptId)?.add(i.conceptId); const active=new Set<string>(),done=new Set<string>(); const visit=(n:string,path:string[])=>{if(active.has(n)){d.push(error("DEPENDENCY",`Dependency cycle detected: ${[...path,n].join(" -> ")}.`,{relatedObjects:[...path,n]}));return;} if(done.has(n))return; active.add(n); for(const x of g.get(n)??[]) visit(x,[...path,n]); active.delete(n);done.add(n)}; for(const n of g.keys())visit(n,[]); }
function stageTypes(s: SeedManifest, d: Diagnostic[]) { const concepts=new Map(s.concepts.map(c=>[c.conceptId,c])); for(const f of s.formulaFamilies) for(const v of f.variants??[]){const inputs=new Map<string,TypeInfo>();for(const i of v.inputs??[])inputs.set(i.name,{dimension:i.unitSemantics.dimension,measure:i.unitSemantics.measureSemantics,currencyRequired:!!i.unitSemantics.currencyRequired});const actual=expressionType(v.expression,inputs,d), expected=concepts.get(v.targetConceptId)?.unitSemantics;if(actual&&expected&&actual.dimension!==expected.dimension)d.push(error("SEMANTIC_TYPE",`Formula output dimension ${actual.dimension} does not match target ${expected.dimension}.`,{formulaId:v.formulaId,variantId:v.variantId,conceptId:v.targetConceptId}));for(const i of v.inputs??[])if(i.temporalBinding?.relation==="PRIOR_COMPARABLE_PERIOD"&&typeof i.temporalBinding.offset!=="number")d.push(error("SEMANTIC_TYPE",`Prior-period input requires an explicit numeric offset: ${i.name}.`,{formulaId:v.formulaId,variantId:v.variantId}));}}
function stageResolution(s: SeedManifest,d:Diagnostic[]){for(const f of s.formulaFamilies){const active=(f.variants??[]).filter((v:any)=>v.status==="ACTIVE");const best=Math.max(...active.map((v:any)=>v.fidelityRank));const ties=active.filter((v:any)=>v.fidelityRank===best);if(ties.length>1)d.push(error("FORMULA_RESOLUTION",`Ambiguous formula precedence for ${f.familyId}.`,{formulaId:ties[0].formulaId,relatedObjects:ties.map((v:any)=>v.variantId)}));}}
function stageReachability(s:SeedManifest,d:Diagnostic[]){const formulas=new Map<string,number>();for(const f of s.formulaFamilies)for(const v of f.variants??[])formulas.set(v.targetConceptId,(formulas.get(v.targetConceptId)??0)+1);for(const c of s.concepts){const derived=c.role==="DERIVED"||c.role==="INTERMEDIATE";if(derived&&!formulas.has(c.conceptId))d.push(error("REACHABILITY",`Derived/intermediate concept has no formula family: ${c.conceptId}.`,{conceptId:c.conceptId}));if(c.role==="PRIMITIVE_INPUT"&&formulas.has(c.conceptId))d.push(error("REACHABILITY",`Primitive input has a derived formula family: ${c.conceptId}.`,{conceptId:c.conceptId}));}}
function stageConsistency(s:SeedManifest,d:Diagnostic[]){const ids=new Set(s.concepts.map(c=>c.conceptId));for(const c of s.constraints)for(const id of c.referencedConceptIds??[])if(!ids.has(id))d.push(error("CONSISTENCY",`Constraint references unknown concept: ${id}.`,{relatedObjects:[c.constraintId,id]}));}
export function compileOntology(seed:SeedManifest){const d:Diagnostic[]=[];stageLexical(seed,d);stageContext(seed,d);stageReferences(seed,d);stageDependencies(seed,d);stageTypes(seed,d);stageResolution(seed,d);stageReachability(seed,d);stageConsistency(seed,d);if(d.some(x=>x.severity==="ERROR"))return{diagnostics:d};const unsigned={releaseId:`ontrel_${seed.manifestId}`,semanticVersion:seed.semanticVersion,ontologyVersion:seed.ontologyVersion,compilerVersion:COMPILER_VERSION,publishedAt:"",effectiveDuring:{start:"2026-01-01",boundarySemantics:"[start,end)"},concepts:seed.concepts,relationships:seed.relationships,formulaFamilies:seed.formulaFamilies,constraints:seed.constraints,sourceReferences:seed.sourceReferences};const artifactHash=`sha256:${createHash("sha256").update(stable(unsigned)).digest("hex")}`;return{artifact:{...unsigned,artifactHash},diagnostics:d};}
